/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicConsentRouteImport } from './routes/api/public/consent'
import { Route as ApiPublicContactsRouteImport } from './routes/api/public/contacts'
import { Route as ApiPublicAuthLoginRouteImport } from './routes/api/public/auth.login'
import { Route as ApiPublicAuthSignupRouteImport } from './routes/api/public/auth.signup'
import { Route as ApiPublicBaselinesSyncRouteImport } from './routes/api/public/baselines.sync'
import { Route as ApiPublicContactsIdRouteImport } from './routes/api/public/contacts.$id'
import { Route as ApiPublicMonitoringLogRouteImport } from './routes/api/public/monitoring.log'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConsentRoute = ApiPublicConsentRouteImport.update({
  id: '/api/public/consent',
  path: '/api/public/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactsRoute = ApiPublicContactsRouteImport.update({
  id: '/api/public/contacts',
  path: '/api/public/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthLoginRoute = ApiPublicAuthLoginRouteImport.update({
  id: '/api/public/auth/login',
  path: '/api/public/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthSignupRoute = ApiPublicAuthSignupRouteImport.update({
  id: '/api/public/auth/signup',
  path: '/api/public/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBaselinesSyncRoute = ApiPublicBaselinesSyncRouteImport.update({
  id: '/api/public/baselines/sync',
  path: '/api/public/baselines/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactsIdRoute = ApiPublicContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicContactsRoute,
} as any)
const ApiPublicMonitoringLogRoute = ApiPublicMonitoringLogRouteImport.update({
  id: '/api/public/monitoring/log',
  path: '/api/public/monitoring/log',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/consent': typeof ApiPublicConsentRoute
  '/api/public/contacts': typeof ApiPublicContactsRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/baselines/sync': typeof ApiPublicBaselinesSyncRoute
  '/api/public/contacts/$id': typeof ApiPublicContactsIdRoute
  '/api/public/monitoring/log': typeof ApiPublicMonitoringLogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/consent': typeof ApiPublicConsentRoute
  '/api/public/contacts': typeof ApiPublicContactsRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/baselines/sync': typeof ApiPublicBaselinesSyncRoute
  '/api/public/contacts/$id': typeof ApiPublicContactsIdRoute
  '/api/public/monitoring/log': typeof ApiPublicMonitoringLogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/consent': typeof ApiPublicConsentRoute
  '/api/public/contacts': typeof ApiPublicContactsRouteWithChildren
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/baselines/sync': typeof ApiPublicBaselinesSyncRoute
  '/api/public/contacts/$id': typeof ApiPublicContactsIdRoute
  '/api/public/monitoring/log': typeof ApiPublicMonitoringLogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/consent'
    | '/api/public/contacts'
    | '/api/public/auth/login'
    | '/api/public/auth/signup'
    | '/api/public/baselines/sync'
    | '/api/public/contacts/$id'
    | '/api/public/monitoring/log'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/consent'
    | '/api/public/contacts'
    | '/api/public/auth/login'
    | '/api/public/auth/signup'
    | '/api/public/baselines/sync'
    | '/api/public/contacts/$id'
    | '/api/public/monitoring/log'
  id:
    | '__root__'
    | '/'
    | '/api/public/consent'
    | '/api/public/contacts'
    | '/api/public/auth/login'
    | '/api/public/auth/signup'
    | '/api/public/baselines/sync'
    | '/api/public/contacts/$id'
    | '/api/public/monitoring/log'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicConsentRoute: typeof ApiPublicConsentRoute
  ApiPublicContactsRoute: typeof ApiPublicContactsRouteWithChildren
  ApiPublicAuthLoginRoute: typeof ApiPublicAuthLoginRoute
  ApiPublicAuthSignupRoute: typeof ApiPublicAuthSignupRoute
  ApiPublicBaselinesSyncRoute: typeof ApiPublicBaselinesSyncRoute
  ApiPublicMonitoringLogRoute: typeof ApiPublicMonitoringLogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consent': {
      id: '/api/public/consent'
      path: '/api/public/consent'
      fullPath: '/api/public/consent'
      preLoaderRoute: typeof ApiPublicConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contacts': {
      id: '/api/public/contacts'
      path: '/api/public/contacts'
      fullPath: '/api/public/contacts'
      preLoaderRoute: typeof ApiPublicContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/login': {
      id: '/api/public/auth/login'
      path: '/api/public/auth/login'
      fullPath: '/api/public/auth/login'
      preLoaderRoute: typeof ApiPublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/signup': {
      id: '/api/public/auth/signup'
      path: '/api/public/auth/signup'
      fullPath: '/api/public/auth/signup'
      preLoaderRoute: typeof ApiPublicAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/baselines/sync': {
      id: '/api/public/baselines/sync'
      path: '/api/public/baselines/sync'
      fullPath: '/api/public/baselines/sync'
      preLoaderRoute: typeof ApiPublicBaselinesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contacts/$id': {
      id: '/api/public/contacts/$id'
      path: '/$id'
      fullPath: '/api/public/contacts/$id'
      preLoaderRoute: typeof ApiPublicContactsIdRouteImport
      parentRoute: typeof ApiPublicContactsRoute
    }
    '/api/public/monitoring/log': {
      id: '/api/public/monitoring/log'
      path: '/api/public/monitoring/log'
      fullPath: '/api/public/monitoring/log'
      preLoaderRoute: typeof ApiPublicMonitoringLogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicContactsRouteChildren {
  ApiPublicContactsIdRoute: typeof ApiPublicContactsIdRoute
}

const ApiPublicContactsRouteChildren: ApiPublicContactsRouteChildren = {
  ApiPublicContactsIdRoute: ApiPublicContactsIdRoute,
}

const ApiPublicContactsRouteWithChildren =
  ApiPublicContactsRoute._addFileChildren(ApiPublicContactsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicConsentRoute: ApiPublicConsentRoute,
  ApiPublicContactsRoute: ApiPublicContactsRouteWithChildren,
  ApiPublicAuthLoginRoute: ApiPublicAuthLoginRoute,
  ApiPublicAuthSignupRoute: ApiPublicAuthSignupRoute,
  ApiPublicBaselinesSyncRoute: ApiPublicBaselinesSyncRoute,
  ApiPublicMonitoringLogRoute: ApiPublicMonitoringLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
