/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as ApiPublicConsentRouteImport } from './routes/api/public/consent'
import { Route as ApiPublicContactsRouteImport } from './routes/api/public/contacts'
import { Route as ApiPublicAlertsTriggerRouteImport } from './routes/api/public/alerts.trigger'
import { Route as ApiPublicAuthCalibrateRouteImport } from './routes/api/public/auth.calibrate'
import { Route as ApiPublicAuthLoginRouteImport } from './routes/api/public/auth.login'
import { Route as ApiPublicAuthRecalibrateRouteImport } from './routes/api/public/auth.recalibrate'
import { Route as ApiPublicAuthSignupRouteImport } from './routes/api/public/auth.signup'
import { Route as ApiPublicAuthVerifyRouteImport } from './routes/api/public/auth.verify'
import { Route as ApiPublicBaselinesSyncRouteImport } from './routes/api/public/baselines.sync'
import { Route as ApiPublicContactsIdRouteImport } from './routes/api/public/contacts.$id'
import { Route as ApiPublicMonitoringLogRouteImport } from './routes/api/public/monitoring.log'
import { Route as ApiPublicUserProfileRouteImport } from './routes/api/public/user.profile'
import { Route as ApiPublicAlertsIdDismissRouteImport } from './routes/api/public/alerts.$id.dismiss'
import { Route as ApiPublicAlertsIdNotifyRouteImport } from './routes/api/public/alerts.$id.notify'
import { Route as ApiPublicAlertsIdStatusRouteImport } from './routes/api/public/alerts.$id.status'
import { Route as ApiPublicContactsIdResendVerificationRouteImport } from './routes/api/public/contacts.$id.resend-verification'
import { Route as ApiPublicContactsIdSendVerificationRouteImport } from './routes/api/public/contacts.$id.send-verification'
import { Route as ApiPublicContactsIdVerifyRouteImport } from './routes/api/public/contacts.$id.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicConsentRoute = ApiPublicConsentRouteImport.update({
  id: '/api/public/consent',
  path: '/api/public/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactsRoute = ApiPublicContactsRouteImport.update({
  id: '/api/public/contacts',
  path: '/api/public/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertsTriggerRoute = ApiPublicAlertsTriggerRouteImport.update({
  id: '/api/public/alerts/trigger',
  path: '/api/public/alerts/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthCalibrateRoute = ApiPublicAuthCalibrateRouteImport.update({
  id: '/api/public/auth/calibrate',
  path: '/api/public/auth/calibrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthLoginRoute = ApiPublicAuthLoginRouteImport.update({
  id: '/api/public/auth/login',
  path: '/api/public/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthRecalibrateRoute =
  ApiPublicAuthRecalibrateRouteImport.update({
    id: '/api/public/auth/recalibrate',
    path: '/api/public/auth/recalibrate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthSignupRoute = ApiPublicAuthSignupRouteImport.update({
  id: '/api/public/auth/signup',
  path: '/api/public/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthVerifyRoute = ApiPublicAuthVerifyRouteImport.update({
  id: '/api/public/auth/verify',
  path: '/api/public/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBaselinesSyncRoute = ApiPublicBaselinesSyncRouteImport.update({
  id: '/api/public/baselines/sync',
  path: '/api/public/baselines/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactsIdRoute = ApiPublicContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicContactsRoute,
} as any)
const ApiPublicMonitoringLogRoute = ApiPublicMonitoringLogRouteImport.update({
  id: '/api/public/monitoring/log',
  path: '/api/public/monitoring/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUserProfileRoute = ApiPublicUserProfileRouteImport.update({
  id: '/api/public/user/profile',
  path: '/api/public/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertsIdDismissRoute =
  ApiPublicAlertsIdDismissRouteImport.update({
    id: '/api/public/alerts/$id/dismiss',
    path: '/api/public/alerts/$id/dismiss',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAlertsIdNotifyRoute = ApiPublicAlertsIdNotifyRouteImport.update({
  id: '/api/public/alerts/$id/notify',
  path: '/api/public/alerts/$id/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertsIdStatusRoute = ApiPublicAlertsIdStatusRouteImport.update({
  id: '/api/public/alerts/$id/status',
  path: '/api/public/alerts/$id/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactsIdResendVerificationRoute =
  ApiPublicContactsIdResendVerificationRouteImport.update({
    id: '/resend-verification',
    path: '/resend-verification',
    getParentRoute: () => ApiPublicContactsIdRoute,
  } as any)
const ApiPublicContactsIdSendVerificationRoute =
  ApiPublicContactsIdSendVerificationRouteImport.update({
    id: '/send-verification',
    path: '/send-verification',
    getParentRoute: () => ApiPublicContactsIdRoute,
  } as any)
const ApiPublicContactsIdVerifyRoute =
  ApiPublicContactsIdVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiPublicContactsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/api/public/consent': typeof ApiPublicConsentRoute
  '/api/public/contacts': typeof ApiPublicContactsRouteWithChildren
  '/api/public/alerts/trigger': typeof ApiPublicAlertsTriggerRoute
  '/api/public/auth/calibrate': typeof ApiPublicAuthCalibrateRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/recalibrate': typeof ApiPublicAuthRecalibrateRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/auth/verify': typeof ApiPublicAuthVerifyRoute
  '/api/public/baselines/sync': typeof ApiPublicBaselinesSyncRoute
  '/api/public/contacts/$id': typeof ApiPublicContactsIdRouteWithChildren
  '/api/public/monitoring/log': typeof ApiPublicMonitoringLogRoute
  '/api/public/user/profile': typeof ApiPublicUserProfileRoute
  '/api/public/alerts/$id/dismiss': typeof ApiPublicAlertsIdDismissRoute
  '/api/public/alerts/$id/notify': typeof ApiPublicAlertsIdNotifyRoute
  '/api/public/alerts/$id/status': typeof ApiPublicAlertsIdStatusRoute
  '/api/public/contacts/$id/resend-verification': typeof ApiPublicContactsIdResendVerificationRoute
  '/api/public/contacts/$id/send-verification': typeof ApiPublicContactsIdSendVerificationRoute
  '/api/public/contacts/$id/verify': typeof ApiPublicContactsIdVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/api/public/consent': typeof ApiPublicConsentRoute
  '/api/public/contacts': typeof ApiPublicContactsRouteWithChildren
  '/api/public/alerts/trigger': typeof ApiPublicAlertsTriggerRoute
  '/api/public/auth/calibrate': typeof ApiPublicAuthCalibrateRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/recalibrate': typeof ApiPublicAuthRecalibrateRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/auth/verify': typeof ApiPublicAuthVerifyRoute
  '/api/public/baselines/sync': typeof ApiPublicBaselinesSyncRoute
  '/api/public/contacts/$id': typeof ApiPublicContactsIdRouteWithChildren
  '/api/public/monitoring/log': typeof ApiPublicMonitoringLogRoute
  '/api/public/user/profile': typeof ApiPublicUserProfileRoute
  '/api/public/alerts/$id/dismiss': typeof ApiPublicAlertsIdDismissRoute
  '/api/public/alerts/$id/notify': typeof ApiPublicAlertsIdNotifyRoute
  '/api/public/alerts/$id/status': typeof ApiPublicAlertsIdStatusRoute
  '/api/public/contacts/$id/resend-verification': typeof ApiPublicContactsIdResendVerificationRoute
  '/api/public/contacts/$id/send-verification': typeof ApiPublicContactsIdSendVerificationRoute
  '/api/public/contacts/$id/verify': typeof ApiPublicContactsIdVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/api/public/consent': typeof ApiPublicConsentRoute
  '/api/public/contacts': typeof ApiPublicContactsRouteWithChildren
  '/api/public/alerts/trigger': typeof ApiPublicAlertsTriggerRoute
  '/api/public/auth/calibrate': typeof ApiPublicAuthCalibrateRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/recalibrate': typeof ApiPublicAuthRecalibrateRoute
  '/api/public/auth/signup': typeof ApiPublicAuthSignupRoute
  '/api/public/auth/verify': typeof ApiPublicAuthVerifyRoute
  '/api/public/baselines/sync': typeof ApiPublicBaselinesSyncRoute
  '/api/public/contacts/$id': typeof ApiPublicContactsIdRouteWithChildren
  '/api/public/monitoring/log': typeof ApiPublicMonitoringLogRoute
  '/api/public/user/profile': typeof ApiPublicUserProfileRoute
  '/api/public/alerts/$id/dismiss': typeof ApiPublicAlertsIdDismissRoute
  '/api/public/alerts/$id/notify': typeof ApiPublicAlertsIdNotifyRoute
  '/api/public/alerts/$id/status': typeof ApiPublicAlertsIdStatusRoute
  '/api/public/contacts/$id/resend-verification': typeof ApiPublicContactsIdResendVerificationRoute
  '/api/public/contacts/$id/send-verification': typeof ApiPublicContactsIdSendVerificationRoute
  '/api/public/contacts/$id/verify': typeof ApiPublicContactsIdVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/api/public/consent'
    | '/api/public/contacts'
    | '/api/public/alerts/trigger'
    | '/api/public/auth/calibrate'
    | '/api/public/auth/login'
    | '/api/public/auth/recalibrate'
    | '/api/public/auth/signup'
    | '/api/public/auth/verify'
    | '/api/public/baselines/sync'
    | '/api/public/contacts/$id'
    | '/api/public/monitoring/log'
    | '/api/public/user/profile'
    | '/api/public/alerts/$id/dismiss'
    | '/api/public/alerts/$id/notify'
    | '/api/public/alerts/$id/status'
    | '/api/public/contacts/$id/resend-verification'
    | '/api/public/contacts/$id/send-verification'
    | '/api/public/contacts/$id/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/api/public/consent'
    | '/api/public/contacts'
    | '/api/public/alerts/trigger'
    | '/api/public/auth/calibrate'
    | '/api/public/auth/login'
    | '/api/public/auth/recalibrate'
    | '/api/public/auth/signup'
    | '/api/public/auth/verify'
    | '/api/public/baselines/sync'
    | '/api/public/contacts/$id'
    | '/api/public/monitoring/log'
    | '/api/public/user/profile'
    | '/api/public/alerts/$id/dismiss'
    | '/api/public/alerts/$id/notify'
    | '/api/public/alerts/$id/status'
    | '/api/public/contacts/$id/resend-verification'
    | '/api/public/contacts/$id/send-verification'
    | '/api/public/contacts/$id/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/home'
    | '/api/public/consent'
    | '/api/public/contacts'
    | '/api/public/alerts/trigger'
    | '/api/public/auth/calibrate'
    | '/api/public/auth/login'
    | '/api/public/auth/recalibrate'
    | '/api/public/auth/signup'
    | '/api/public/auth/verify'
    | '/api/public/baselines/sync'
    | '/api/public/contacts/$id'
    | '/api/public/monitoring/log'
    | '/api/public/user/profile'
    | '/api/public/alerts/$id/dismiss'
    | '/api/public/alerts/$id/notify'
    | '/api/public/alerts/$id/status'
    | '/api/public/contacts/$id/resend-verification'
    | '/api/public/contacts/$id/send-verification'
    | '/api/public/contacts/$id/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicConsentRoute: typeof ApiPublicConsentRoute
  ApiPublicContactsRoute: typeof ApiPublicContactsRouteWithChildren
  ApiPublicAlertsTriggerRoute: typeof ApiPublicAlertsTriggerRoute
  ApiPublicAuthCalibrateRoute: typeof ApiPublicAuthCalibrateRoute
  ApiPublicAuthLoginRoute: typeof ApiPublicAuthLoginRoute
  ApiPublicAuthRecalibrateRoute: typeof ApiPublicAuthRecalibrateRoute
  ApiPublicAuthSignupRoute: typeof ApiPublicAuthSignupRoute
  ApiPublicAuthVerifyRoute: typeof ApiPublicAuthVerifyRoute
  ApiPublicBaselinesSyncRoute: typeof ApiPublicBaselinesSyncRoute
  ApiPublicMonitoringLogRoute: typeof ApiPublicMonitoringLogRoute
  ApiPublicUserProfileRoute: typeof ApiPublicUserProfileRoute
  ApiPublicAlertsIdDismissRoute: typeof ApiPublicAlertsIdDismissRoute
  ApiPublicAlertsIdNotifyRoute: typeof ApiPublicAlertsIdNotifyRoute
  ApiPublicAlertsIdStatusRoute: typeof ApiPublicAlertsIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/consent': {
      id: '/api/public/consent'
      path: '/api/public/consent'
      fullPath: '/api/public/consent'
      preLoaderRoute: typeof ApiPublicConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contacts': {
      id: '/api/public/contacts'
      path: '/api/public/contacts'
      fullPath: '/api/public/contacts'
      preLoaderRoute: typeof ApiPublicContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts/trigger': {
      id: '/api/public/alerts/trigger'
      path: '/api/public/alerts/trigger'
      fullPath: '/api/public/alerts/trigger'
      preLoaderRoute: typeof ApiPublicAlertsTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/calibrate': {
      id: '/api/public/auth/calibrate'
      path: '/api/public/auth/calibrate'
      fullPath: '/api/public/auth/calibrate'
      preLoaderRoute: typeof ApiPublicAuthCalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/login': {
      id: '/api/public/auth/login'
      path: '/api/public/auth/login'
      fullPath: '/api/public/auth/login'
      preLoaderRoute: typeof ApiPublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/recalibrate': {
      id: '/api/public/auth/recalibrate'
      path: '/api/public/auth/recalibrate'
      fullPath: '/api/public/auth/recalibrate'
      preLoaderRoute: typeof ApiPublicAuthRecalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/signup': {
      id: '/api/public/auth/signup'
      path: '/api/public/auth/signup'
      fullPath: '/api/public/auth/signup'
      preLoaderRoute: typeof ApiPublicAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/verify': {
      id: '/api/public/auth/verify'
      path: '/api/public/auth/verify'
      fullPath: '/api/public/auth/verify'
      preLoaderRoute: typeof ApiPublicAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/baselines/sync': {
      id: '/api/public/baselines/sync'
      path: '/api/public/baselines/sync'
      fullPath: '/api/public/baselines/sync'
      preLoaderRoute: typeof ApiPublicBaselinesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contacts/$id': {
      id: '/api/public/contacts/$id'
      path: '/$id'
      fullPath: '/api/public/contacts/$id'
      preLoaderRoute: typeof ApiPublicContactsIdRouteImport
      parentRoute: typeof ApiPublicContactsRoute
    }
    '/api/public/monitoring/log': {
      id: '/api/public/monitoring/log'
      path: '/api/public/monitoring/log'
      fullPath: '/api/public/monitoring/log'
      preLoaderRoute: typeof ApiPublicMonitoringLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/user/profile': {
      id: '/api/public/user/profile'
      path: '/api/public/user/profile'
      fullPath: '/api/public/user/profile'
      preLoaderRoute: typeof ApiPublicUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts/$id/dismiss': {
      id: '/api/public/alerts/$id/dismiss'
      path: '/api/public/alerts/$id/dismiss'
      fullPath: '/api/public/alerts/$id/dismiss'
      preLoaderRoute: typeof ApiPublicAlertsIdDismissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts/$id/notify': {
      id: '/api/public/alerts/$id/notify'
      path: '/api/public/alerts/$id/notify'
      fullPath: '/api/public/alerts/$id/notify'
      preLoaderRoute: typeof ApiPublicAlertsIdNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts/$id/status': {
      id: '/api/public/alerts/$id/status'
      path: '/api/public/alerts/$id/status'
      fullPath: '/api/public/alerts/$id/status'
      preLoaderRoute: typeof ApiPublicAlertsIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contacts/$id/resend-verification': {
      id: '/api/public/contacts/$id/resend-verification'
      path: '/resend-verification'
      fullPath: '/api/public/contacts/$id/resend-verification'
      preLoaderRoute: typeof ApiPublicContactsIdResendVerificationRouteImport
      parentRoute: typeof ApiPublicContactsIdRoute
    }
    '/api/public/contacts/$id/send-verification': {
      id: '/api/public/contacts/$id/send-verification'
      path: '/send-verification'
      fullPath: '/api/public/contacts/$id/send-verification'
      preLoaderRoute: typeof ApiPublicContactsIdSendVerificationRouteImport
      parentRoute: typeof ApiPublicContactsIdRoute
    }
    '/api/public/contacts/$id/verify': {
      id: '/api/public/contacts/$id/verify'
      path: '/verify'
      fullPath: '/api/public/contacts/$id/verify'
      preLoaderRoute: typeof ApiPublicContactsIdVerifyRouteImport
      parentRoute: typeof ApiPublicContactsIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicContactsIdRouteChildren {
  ApiPublicContactsIdResendVerificationRoute: typeof ApiPublicContactsIdResendVerificationRoute
  ApiPublicContactsIdSendVerificationRoute: typeof ApiPublicContactsIdSendVerificationRoute
  ApiPublicContactsIdVerifyRoute: typeof ApiPublicContactsIdVerifyRoute
}

const ApiPublicContactsIdRouteChildren: ApiPublicContactsIdRouteChildren = {
  ApiPublicContactsIdResendVerificationRoute:
    ApiPublicContactsIdResendVerificationRoute,
  ApiPublicContactsIdSendVerificationRoute:
    ApiPublicContactsIdSendVerificationRoute,
  ApiPublicContactsIdVerifyRoute: ApiPublicContactsIdVerifyRoute,
}

const ApiPublicContactsIdRouteWithChildren =
  ApiPublicContactsIdRoute._addFileChildren(ApiPublicContactsIdRouteChildren)

interface ApiPublicContactsRouteChildren {
  ApiPublicContactsIdRoute: typeof ApiPublicContactsIdRouteWithChildren
}

const ApiPublicContactsRouteChildren: ApiPublicContactsRouteChildren = {
  ApiPublicContactsIdRoute: ApiPublicContactsIdRouteWithChildren,
}

const ApiPublicContactsRouteWithChildren =
  ApiPublicContactsRoute._addFileChildren(ApiPublicContactsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicConsentRoute: ApiPublicConsentRoute,
  ApiPublicContactsRoute: ApiPublicContactsRouteWithChildren,
  ApiPublicAlertsTriggerRoute: ApiPublicAlertsTriggerRoute,
  ApiPublicAuthCalibrateRoute: ApiPublicAuthCalibrateRoute,
  ApiPublicAuthLoginRoute: ApiPublicAuthLoginRoute,
  ApiPublicAuthRecalibrateRoute: ApiPublicAuthRecalibrateRoute,
  ApiPublicAuthSignupRoute: ApiPublicAuthSignupRoute,
  ApiPublicAuthVerifyRoute: ApiPublicAuthVerifyRoute,
  ApiPublicBaselinesSyncRoute: ApiPublicBaselinesSyncRoute,
  ApiPublicMonitoringLogRoute: ApiPublicMonitoringLogRoute,
  ApiPublicUserProfileRoute: ApiPublicUserProfileRoute,
  ApiPublicAlertsIdDismissRoute: ApiPublicAlertsIdDismissRoute,
  ApiPublicAlertsIdNotifyRoute: ApiPublicAlertsIdNotifyRoute,
  ApiPublicAlertsIdStatusRoute: ApiPublicAlertsIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
